- vagrant/ansible/roles/client.test/tasks/main.yml
Make use of the new sanity test target in the sit-test-cases repo
https://github.com/samba-in-kubernetes/sit-test-cases/pull/3
This is expected to be used by the CI environment in the sit-environment repo as we would like a quick turnaround when testing in the CI environment and we only need to validate the correctness of the sit-environment repo.
This was bought about because changes in the samba and clustered filesystem repo can cause failures in the smbtorture tests for no fault in the sit-environment repository.
To set up sanity testing only, we need to pass the 'test_sanity_only=1' in the EXTRA_VARS in the CI environment.
depends on #1 samba-in-kubernetes/sit-test-cases#3
> Sanity tests for CI

- vagrant/ansible/roles/ctdb.setup/tasks/main.yml
Since [v4.16 release](https://www.samba.org/samba/history/samba-4.16.0.html) CTDB renamed "recovery lock" to "cluster lock". Therefore use "cluster lock" in ctdb.conf replacing "recovery lock".
> ctdb.setup: Use 'cluster lock' instead of 'recovery lock'

- vagrant/roles/local.defaults/tasks/centos8.yml
Changes in the rpm package specs required that the rpm package has to be updated first before we can updated the rest.
This doesn't seem to cause a problem in the CentOS environment which seems to use an updated centos8 image. However this does cause problems in devel environments when performing updates of the centos8 virtual machines.
> Failure when updating CentOS 8 vagrant vms.

- vagrant/ansible/roles/client.prep/tasks/centos7.yml
- vagrant/ansible/roles/client.prep/tasks/centos8.yml
We also symlink /usrt/local/bin/pytest to
/usr/bin/pytest-3
This will be used as a test runner for sit-test-cases
> client.prep: Add pytest for clients

- vagrant/ansible/roles/client.prep/tasks/centos7.yml
- vagrant/ansible/roles/client.prep/tasks/centos8.yml
This can be used by the testcase runners to test against a SMB server.
> client.prep: provide smbclient on the clients

- README.md
Samba Integration was moved from gluster repo into this independent repo. Updating the links so that they are relavant to this new repo.
> Update README.md with new links

- vagrant/Makefile
- vagrant/ansible/roles/client.test.prep/tasks/main.yml
- vagrant/ansible/roles/client.test/tasks/main.yml
Change the directory in which the sit-test-cases are cloned from samba-integration-tests to
sit-test-cases
> client.test.prep: Change test directory to sit-test-cases

- vagrant/ansible/roles/client.test/tasks/main.yml
At the moment, if the tests are successful, the output is not printed. With the planned performance tests, we would like the output printed even when the tests are successful.
> client.test: print test output

- docs/backends.md
- vagrant/roles/local.defaults/templates/config.yml.j2
- vagrant/roles/local.defaults/vars/main.yml
The mapping is really unnecessary because the name is always mapped to itself.
> Remove OS and backend name mappings

- vagrant/roles/local.defaults/templates/config.yml.j2
- vagrant/roles/local.defaults/vars/main.yml
Some properties for each supported OS are added so that they can be used in conditionals and other places. This can help reduce code duplication.
> Add OS properties in configuration

- vagrant/ansible/roles/sit.cephfs/tasks/server/centos.yml
- vagrant/ansible/roles/sit.cephfs/tasks/server/main.yml
When cephadm is installed directly from the latest GitHub version, no dependency check is done. To avoid missing some required depencencies, cephadm is now installed from the same repo as the ceph-common package, which should be recent enough.
> Fix cephadm dependencies issues

- vagrant/ansible/roles/client.prep/tasks/centos.yml
When running sit-tests-cases we need python's tox utility.
> Install 'tox' package

- vagrant/ansible.cfg
- vagrant/ansible/ansible.cfg
Create an ansible.cfg file to configure ansible's playbooks behavior:
- Fail immediately as soon as any task fails
By default ansible continues executing tasks as long as at least one host has succeeded. In out environment this doesn't make sense because we need all hosts prepared to run tests.
- Add timing
This will be useful to know at which time each task has started and be able to match it with logs in case of issues. It will also give an idea of which tasks consume more time, which can be used to try to optimize the playbooks.
> Add ansible.cfg

- vagrant/roles/sit.glusterfs/tasks/setup/centos.yml
Recently the following error is seen while trying to install ansible collections:
> [WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got
an unexpected error when getting available versions of collection community.general:
'/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
ERROR! Unexpected Exception, this is probably a bug:
'/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
We are already stuck with ansible version from 2.12.x series due to another [issue](https://github.com/gluster/gluster-ansible-infra/issues/135) from gluster-ansible-infra and fix for the above error is only available from [v2.12.8](https://github.com/ansible/ansible/issues/81830#issuecomment-1743199288). Given that the fixed …
> sit.glusterfs: Install ansible collections with --no-cache

- vagrant/roles/sit.glusterfs/tasks/setup/centos.yml
- vagrant/roles/sit.glusterfs/tasks/setup/centos8.yml
- vagrant/roles/sit.glusterfs/tasks/setup/centos9.yml
Now that the required [fixes](https://github.com/gluster/gluster-ansible-infra/pull/136) are in for gluster-ansible we could use latest ansible packages.
> sit.glusterfs/setup: Install latest available ansible version

- playbooks/ansible/roles/tests/tasks/main.yml
- playbooks/ansible/roles/tests/tasks/run-test.yml
The current approach detects failures but does continue with other tests. This is problematic because the ansible playbook execution completes successfully while there could have been some failed tests.
This patch forces a failure when any test fails. This will fix the issue until a better test failure reporting is implemented.
fixes #51
> Force a failure if some test fails

- devel/inventory
Fix symlink to inventory in the devel directory. This allows us to use the ansible scripts in the devel directory.
> devel: fix inventory symlink

- playbooks/ansible/roles/samba.setup/tasks/main.yml
> samba.setup: Ensure healthy cluster before `smbd` restart

- playbooks/roles/local.defaults/vars/main.yml
Upgraded number of CPUs and memory for all backends:
```
Storage node       Client node
XFS          4 CPUs / 4 GiB    4 CPUs / 4 GiB
GlusterFS    8 CPUs / 8 GiB    4 CPUs / 4 GiB
CephFS       8 CPUs / 8 GiB    4 CPUs / 4 GiB
```
> Increase VM specs

- playbooks/roles/config.collect/tasks/main.yml
- playbooks/roles/local.defaults/templates/config.yml.j2
* Instead of processed backend name use the raw `backend` environment variable value for better discovery of statedir.
- Such a change was the missing piece, especially with `cephfs.vfs` where jenkins used to search for _/tmp/sit.cephfs.vfs_statedump_ but the actual directory is named _sit.cephfs_statedump_.
* In those situations where environment was not setup correctly we fail to run any tests. This would mean that test-info.yml file is not linked and subsequent task to copy it fails. Therefore make sure that we collect rest of the logs and configuration by ignoring the errors while copying the test-info file.
> statedump: Few cleanup changes

- playbooks/ansible/roles/tests/tasks/log.yml
Since we copy the required playbooks from host, _site-tests.log_ was always created within setup machine. As a result statedump process failed to copy it from setup machine. Therefore allow it to be created under _/var/log_ so that statedump process can collect it from the client machine.
> tests: Fix the location of site-tests.log

- playbooks/roles/local.defaults/tasks/main.yml
- playbooks/roles/local.defaults/templates/config.yml.j2
- playbooks/settings.yml
This patch provides a way to automatically assign a portion of the memory and CPUs to the sit-environment and proportionally distribute it among the VMs that will be created based on a per-VM weight defined in the environment configuration.
Two new extra vars have been defined that can override how many resources are assigned to sit-environment:
`memory`: Percentage of the free memory assigned to sit-environment (default: 50)
`cpu`: Percentage of the available cores assigned to sit-environment (default: 100)
> Dynamically adjust the amount of memory and CPUs assigned to each VM

- playbooks/roles/sit.xfs/tasks/config/main.yml
`sit.xfs` role failed to include _/etc/samba_ and _/etc/ctdb_ configuration directories during statedump process.
> sit.xfs: Copy Samba-CTDB configuration from cluster nodes

- playbooks/ansible/roles/test.sit-test-cases/tasks/main.yml
Instead of cluttering the jenkins job console output with detailed test results we could redirect everything to a separate file and make it available as artifacts for each job. Simplest way to achieve this redirection is to make use of `&>`(see [section 3.6.4 bash manual](https://www.gnu.org/software/bash/manual/html_node/Redirections.html)) to include both STDOUT and STDERR. Location of such an output file is chosen to be under _/var/log_ so that it also gets collected as part of statedump process.
> test.sit-test-cases: Redirect test output to a file

- playbooks/ansible/Makefile
- playbooks/ansible/roles/test.sit-test-cases/tasks/main.yml
* smbtorture tests have been configured in https://github.com/samba-in-kubernetes/sit-test-cases/pull/44 to print the results irrespective of the outcome.
* Test output is now redirected to a separate file in https://github.com/samba-in-kubernetes/sit-environment/pull/67, additional debug lines from ansible are no longer required.
Previous change from 15b8f6179f204c4ee3cce755e7fcc4498e0fe9d3 to configure `ANSIBLE_STDOUT_CALLBACK` option can also be avoided as entire results are now available in a separate file.
depends on #67
> client-test: Disable printing test output

- playbooks/environment.sh
_environment.sh_ contains just an `export` statement for `ANSIBLE_INVENTORY` variable. It was added in 6dfc2a4952673bf1e369f5ba5d66a7c83f5866f4 to better work with vagrant environments. But these days inventory file is always specified as part of playbook execution command. Therefore remove `environment.sh` from sources.
> playbooks: Remove unused shell script

- playbooks/roles/local.defaults/tasks/main.yml
It has been a while since XFS was added to the list of supported backends and is known to successfully complete full test runs. On the other side GlusterFS is going through tough times in getting necessary fixes for long pending failures. Let's flip the switch and change the default backend from GlusterFS to XFS.
> local.defaults: Change default backend to XFS

- playbooks/roles/local.defaults/templates/config.yml.j2
Make targets when invoked without explicit mention of `backend` variable leaves behind a single occurrence in config.yml.j2 causing the following failure:
> TASK [local.defaults : Generate config.yml in ansible directory] An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'backend' is undefined. 'backend' is undefined
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'backend' is undefined. 'backend' is undefined"}
Therefore redefine statedump directory name to "sit_statedump".
fixes #72
> local.defaults: Redefine statedump directory name

- playbooks/ansible/cluster-cephfs.yml
- playbooks/ansible/cluster-glusterfs.yml
- playbooks/ansible/cluster-xfs.yml
- playbooks/ansible/roles/client.prep/tasks/main.yml
- playbooks/ansible/roles/client.prep/templates/README.j2
- playbooks/ansible/roles/client.prep/templates/test-info.yml.j2
- playbooks/ansible/roles/ctdb.setup/tasks/main.yml
- playbooks/ansible/roles/samba.setup/tasks/main.yml
- playbooks/ansible/roles/users.setup/tasks/create_users.yml
- playbooks/ansible/roles/users.setup/tasks/main.yml
- playbooks/ansible/setup-cluster.yml
- playbooks/roles/hosts.update/tasks/create_groups.yml
- playbooks/roles/hosts.update/tasks/create_users.yml
- playbooks/roles/hosts.update/tasks/main.yml
- playbooks/roles/local.defaults/templates/config.yml.j2
- playbooks/settings.yml
Instead of defining users inside the private configuration of each backend, the definition has been moved to the global _setting.yml_ file. Additionally, now it's also possible to define groups and group membership.
To support cases where we want a lot of users and/or groups, it's also possible to define them in a very compact way.
> Make definition of users and groups configurable inside settings.yml

- playbooks/ansible/roles/samba.setup/tasks/cephfs/centos.yml
- playbooks/ansible/roles/samba.setup/tasks/cephfs/main.yml
Upon investigation following are the only AVCs from audit logs blocking us from running CephFS VFS integration.
> type=AVC msg=audit(1706499792.666:8328): avc:  denied  { name_connect } for  pid=75570 comm="msgr-worker-1" dest=3300 scontext=system_u:system_r:smbd_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket permissive=1
Even though its misleading `samba_load_libgfapi` seems to be the only SELinux boolean that we require to run integration using VFS module for Ceph in Samba under Enforcing mode. This is clear from the allow rules defined for the boolean as follows:
```
$ sesearch -b samba_load_libgfapi -A
allow smbd_t packet_type:packet recv; [ samba_load_libgfapi ]:True
allow smbd_t packet_type:packet send; [ samba_load_libgfapi ]:True
allow smbd_t …
```
> samba.setup: Run cephfs.vfs integration with SELinux booleans

- .gitignore
- playbooks/roles/local.defaults/tasks/main.yml
- playbooks/roles/local.defaults/templates/config.yml.j2
- playbooks/roles/provisioner.vagrant/templates/Vagrantfile.j2
With this patch it will be possible to define customized settings using user defined files outside of the repository that will override the values from settings.yml.
This can be useful to adapt sit-environment to the personal environment characteristics without having to modify the settings.yml file each time it's updated.
There are two places were personal settings can be defined:
- ~/.site/settings.yml
This file can contain settings used by all sit-environments. This one overrides configurations from settings.yml.
- ./local.yml (normally the root of the repo)
This file can contain settings specific for this instance of the repo. This one overrides configurations from settings.yml and ~/.site/settings.yml.
> Provide support for personal and local settings

- playbooks/ansible/cluster-cephfs.yml
- playbooks/ansible/cluster-glusterfs.yml
- playbooks/ansible/cluster-xfs.yml
- playbooks/ansible/roles/samba.setup/tasks/main.yml
- playbooks/ansible/roles/sit.cephfs/templates/smb_share.conf.j2
- playbooks/ansible/roles/sit.glusterfs/templates/smb_share.conf.j2
- playbooks/ansible/roles/sit.xfs/templates/smb_share.conf.j2
For better coverage of smbtorture tests we require `ignore system acls` enabled for _acl_xattr_ VFS module. This is done to successfully complete those tests where such a lossy translation attempt from NT ACLs to POSIX ACLs would result in failures by design.
fixes #81
> smb_share.conf.j2: Add `ignore system acls` option to vfs_acl_xattr

- playbooks/ansible/roles/client.prep/tasks/centos.yml
Since we have moved to using tox to run tests on the client, we can install the required dependencies from within tox. We do not need to use pip to install the modules on the clients.
> client: do not use pip to install python modules

- playbooks/ansible/cluster-glusterfs.yml
- playbooks/ansible/roles/client.prep/tasks/centos.yml
- playbooks/ansible/roles/client.prep/tasks/main.yml
- playbooks/ansible/roles/common.prep/tasks/main.yml
- playbooks/ansible/roles/ctdb.setup/tasks/cephfs/main.yml
- playbooks/ansible/roles/ctdb.setup/tasks/glusterfs/main.yml
- playbooks/ansible/roles/sit.cephfs/tasks/main.yml
- playbooks/ansible/roles/sit.cephfs/tasks/new_volume.yml
- playbooks/ansible/roles/sit.glusterfs/tasks/main.yml
- playbooks/ansible/roles/sit.glusterfs/tasks/new_volume.yml
- playbooks/roles/provisioner.vagrant/tasks/create/main.yml
This PR makes it possible to directly access the backend filesystem from the client machines bypassing Samba layer.
This is exclusively created for testing purposes since bypassing Samba will most probably cause problems (multiprotocol access is not supported yet), but it will simplify the implementation of some tests.
The backend filesystems are mounted inside _/mnt/backends/_, in a subdirectory with the same name as the samba share.
This is currently implemented using SSHFS, which doesn't support extended attributes, so there may be limitations on what can be done directly on the backend. If needed, this can be improved in the future by using an NFSv4 mount instead of SSHFS.
> Make backend filesystems available from client machines

- playbooks/ansible/roles/ctdb.setup/tasks/glusterfs/main.yml
- playbooks/ansible/roles/samba.setup/tasks/cephfs/main.yml
- playbooks/ansible/roles/samba.setup/tasks/glusterfs/main.yml
- playbooks/ansible/roles/sit.cephfs/tasks/server/main.yml
- playbooks/roles/setup.prep/tasks/centos.yml
- playbooks/roles/setup.prep/tasks/centos8.yml
- playbooks/roles/setup.prep/tasks/centos9.yml
- playbooks/roles/sit.cephfs/tasks/setup/centos8.yml
- playbooks/roles/sit.cephfs/tasks/setup/centos9.yml
- playbooks/roles/sit.cephfs/tasks/setup/main.yml
- playbooks/roles/sit.glusterfs/tasks/setup/centos8.yml
- playbooks/roles/sit.glusterfs/tasks/setup/centos9.yml
- playbooks/roles/sit.glusterfs/tasks/setup/main.yml
Very recently on CentOS Stream 8 ansible version got updated to _v2.16.3_ built with Python 3.12. Due to unavailability of python 3.12 module for _jmespath_ playbook execution is expected to fail. Therefore switch the python module installation from RPMs to pip where it can be versioned.
Additionally due to a regression in `first_found` plugin we switch to absolute paths wherever required to find OS specific files. See https://github.com/ansible/ansible/issues/82695 for more details.
depends on https://github.com/samba-in-kubernetes/samba-centosci/pull/54
> Fixes to adjust with latest ansible v2.16.3

- playbooks/ansible/roles/samba.setup/tasks/cephfs/main.yml
warning:
playbooks/ansible/roles/samba.setup/tasks/cephfs/main.yml
10:121    warning  line too long (121 > 120 characters)  (line-length)
> cephfs/main.yml: Fix a yamllint warning

- playbooks/settings.yml
Client machines can very well run with CentOS 9 and higher. In fact [sit-test-cases](https://github.com/samba-in-kubernetes/sit-test-cases/) has a requirement for Python 3.9 which is by default available with CentOS 9.
> gpfs: Remove CentOS 8 requirement for clients

- playbooks/ansible/roles/samba.setup/tasks/gpfs/main.yml
- playbooks/ansible/roles/sit.gpfs/templates/smb_share.conf.j2
Now it's possible to use the 'vfs' variant of the GPFS backend. With it, the gpfs VFS module is automatically configured to be used by Samba.
The GPFS VFS module dynamically loads libgpfs.so library, which requires access to some resources that are not granted by default by SElinux. The Storage Scale product solves this by running smbd process unconfined, so the same solution has been applied here.
> Add support for 'gpfs.vfs' backend variant

- playbooks/ansible/roles/ctdb.setup/tasks/cephfs/main.yml
- playbooks/ansible/roles/ctdb.setup/tasks/main.yml
- playbooks/ansible/roles/sit.cephfs/tasks/repo/centos.yml
- playbooks/settings.yml
It has been a while since a dedicated helper got added to CTDB for managing cluster locks directly on ceph RADOS. Therefore provide a mechanism to optionally configure it instead of the default shared file system locks.
See [man ctdb_mutex_ceph_rados_helper(7)](https://ctdb.samba.org/manpages/ctdb_mutex_ceph_rados_helper.7.html) for more details.
> ceph: Add optional method to use RADOS helper to manage cluster lock

- devel/inventory
The inventory file location in the playbooks has changed. Fix the symlink so that we can use the ansible scripts from the devel directory again.
> devel: fix symlink to inventory file

- playbooks/ansible/roles/sit.cephfs/templates/smb_share.conf.j2
Use kernel CephFS mounted share path to create the shadow copy using ceph_snapshots module
Refer: https://www.samba.org/samba/docs/4.11/man-html/vfs_ceph_snapshots.8.html
> Expose CephFS snapshots as shadow-copies

- playbooks/ansible/cluster-cephfs.yml
- playbooks/ansible/cluster-glusterfs.yml
- playbooks/ansible/cluster-gpfs.yml
- playbooks/ansible/cluster-xfs.yml
- playbooks/ansible/roles/samba.setup/files/smbd_dac_override.te
- playbooks/ansible/roles/samba.setup/tasks/cephfs/main.yml
- playbooks/ansible/roles/samba.setup/tasks/xfs/main.yml
Following changes are made:
- Remove 'ignore system acls' to keep lossy mapping to POSIX ACLs.
- Configure xattr name to store NT ACLs as "user.NTACL".
We introduce a temporary workaround to allow _smbd_ to assume _cap_dac_override_ when operating as _root_ until official fixes are available.
> samba: Make adjustments to vfs_acl_xattr configuration

- playbooks/settings.yml
All required gluster-ansible packages were recently built and available via fedora copr(epel-9). Make use of the repository to finally switch the platform from EOL CentOS Stream 8.
> settings.yml: Use default OS for GlusterFS nodes

- playbooks/ansible/roles/test.sit-test-cases/tasks/prepare/main.yml
- playbooks/ansible/roles/test.sit-test-cases/templates/test-info.yml.j2
- Remove an unnecessary variable definition.
- Add variant in addition to backend.
depends on https://github.com/samba-in-kubernetes/sit-test-cases/pull/89
> Few improvements to test-info.yml

- playbooks/ansible/roles/samba.setup/templates/smb.conf.j2
* '[kernel share modes](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#KERNELSHAREMODES)' is disabled by default.
>  This parameter defaults to no. Setting it to yes requires a file system module that supports file system sharemodes, otherwise attempts to access files will fail with a sharing violation.
>
> Default: kernel share modes = no 
* '[store dos attributes](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#STOREDOSATTRIBUTES)', which is set by default, assumes 'map archive' to be disabled.
> When this parameter is set it will override the parameters [map hidden](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#MAPHIDDEN), [map system](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#MAPSYSTEM), [map …
> smb.conf: Avoid setting duplicate/ignored options

- playbooks/ansible/cluster-cephfs.yml
- playbooks/ansible/roles/sit.cephfs/tasks/main.yml
- playbooks/ansible/roles/sit.cephfs/templates/ceph.smb.cluster.yml.j2
- playbooks/ansible/roles/sit.cephfs/templates/ceph.smb.share.yml.j2
- playbooks/ansible/roles/test.sit-test-cases/tasks/prepare/main.yml
- playbooks/ansible/setup-cluster.yml
- playbooks/roles/local.defaults/templates/config.yml.j2
- playbooks/settings.yml
- Enable and create samba shares with ceph `smb` mgr module.
- Explicit creation of samba users via _users.setup_ is skipped(achieved through `smb` mgr module).
- Client access directed at node running smb service.
Finally, we have a new backend - **cephfs.mgr.vfs** 😀 .
> Add support for samba setup using ceph `smb` manager module

- playbooks/ansible/roles/samba.setup/tasks/cephfs/main.yml
- playbooks/ansible/roles/samba.setup/tasks/gpfs/main.yml
- playbooks/ansible/roles/sit.cephfs/tasks/repo/centos.yml
- playbooks/ansible/roles/sit.cephfs/templates/ceph.smb.share.yml.j2
- playbooks/ansible/roles/sit.cephfs/templates/smb_share.conf.j2
- playbooks/ansible/roles/sit.gpfs/tasks/main.yml
- playbooks/ansible/roles/sit.gpfs/templates/smb_share.conf.j2
- playbooks/ansible/roles/test.sit-test-cases/tasks/prepare/main.yml
- playbooks/ansible/roles/test.sit-test-cases/templates/test-info.yml.j2
- playbooks/roles/local.defaults/templates/config.yml.j2
- playbooks/settings.yml
Key considerations:
- _**cephfs**_ and _**cephfs.vfs**_ are combined together under _**cephfs**_.
- _**cephfs.mgr.vfs**_ becomes _**cephfs.mgr**_ when shares are configured using ceph smb mgr module.
- A new `methods` field to indicate how variations of each share section are to be configured within _smb.conf_.
- Special cases:
- kernel client approach is not yet supported by ceph mgr module. Accordingly we skip this variation.
- gpfs `scale` variant configuration is always based on _vfs_.  Thus we skip iterating over available methods.
fixes #101
> Group possible backend share configurations under same environment

- playbooks/ansible/roles/sit.cephfs/templates/smb_share.conf.j2
- playbooks/settings.yml
> sit.cephfs: Add share configured with `vfs_ceph_new`(non-mgr)

- playbooks/ansible/roles/sit.cephfs/templates/ceph.smb.share.yml.j2
- playbooks/roles/local.defaults/templates/config.yml.j2
- playbooks/settings.yml
depends on https://github.com/ceph/ceph/pull/58994
depends on #116
> sit.cephfs: Add share configured with `vfs_ceph_new`(mgr)

- playbooks/ansible/cluster-cephfs.yml
- playbooks/ansible/roles/sit.cephfs/templates/ceph.smb.cluster.yml.j2
- playbooks/ansible/roles/test.sit-test-cases/tasks/prepare/main.yml
Clustering support is now natively available with ceph smb mgr module. Make use of `clustering` option to _ceph.smb.cluster_ resource definition along with the placement count and required public addresses.
> sit.cephfs: Enable clustering for mgr variant

- playbooks/ansible/roles/sit.gpfs/tasks/server/redhat.yml
The most recent release of GPFS (5.2.1.0) requieres python 3.8+. Since this version doesn't still work with CentOS Stream 9, we install the highest python version available in CentOS 8.
Fixes: #123
> gpfs: Use python 3.9 in CentOS 8

- playbooks/ansible/roles/ctdb.setup/tasks/main.yml
- playbooks/ansible/roles/samba.setup/files/smbd_connect_proxy.te
- playbooks/ansible/roles/samba.setup/tasks/cephfs/main.yml
- playbooks/ansible/roles/samba.setup/tasks/custom_selinux_policy.yml
- playbooks/ansible/roles/samba.setup/tasks/xfs/main.yml
- playbooks/ansible/roles/sit.cephfs/tasks/git/centos.yml
- playbooks/ansible/roles/sit.cephfs/tasks/repo/centos.yml
- playbooks/ansible/roles/sit.cephfs/templates/smb_share.conf.j2
- playbooks/settings.yml
With https://github.com/ceph/ceph/pull/58376 merged we have the libcephfs proxy library and its dependencies available with upstream. Therefore we try to create an additional share with proxy enabled.
Please note that even though we have the required `Recommends:` for dependent packages defined in the [rpm spec file](https://github.com/ceph/ceph/blob/main/ceph.spec.in)(and visible with built rpms) there is an extra mile that DNF takes as part of [libsolv](https://github.com/openSUSE/libsolv) library which prevents it from being presented as installable weak dependencies as one would expect as per the [docs](https://docs.fedoraproject.org/en-US/packaging-guidelines/WeakDependencies/).
depends on https://github.com/ceph/ceph/pull/61537
> sit.cephfs: Add proxy enbaled shares with `vfs_ceph_new`(non-mgr)

- playbooks/ansible/roles/sit.cephfs/templates/ceph.smb.share.yml.j2
- playbooks/ansible/roles/sit.cephfs/templates/smb_share.conf.j2
- playbooks/roles/local.defaults/templates/config.yml.j2
- playbooks/settings.yml
With https://github.com/ceph/ceph/pull/59740 merged ceph smb manager module is capable of creating shares with `ceph_new:proxy` module option set to "yes". Thus an additional share with proxy support is created for _mgr_ variant.
> sit.cephfs: Add proxy enbaled shares with `vfs_ceph_new` (mgr)

- playbooks/ansible/roles/samba.setup/files/smbd_connect_proxy.te
The implementation of the negotiation support requires additional selinux permissions to work correctly.
fixes https://github.com/samba-in-kubernetes/sit-test-cases/issues/98
> samba.setup: update selinux policy to support negotiation

- playbooks/ansible/roles/samba.setup/tasks/cephfs/main.yml
Override the default glibc buffering for `STDOUT` and `STDERR` so that the log contents are visible line by line as soon as they are printed by the daemon. In order to avoid the message "nohup: ignoring input" getting printed on to log file we explicitly redirect `STDIN` to _/dev/null_.
> cephfs: Modify libcephfsd buffering mode for `STDOUT` and `STDERR`

- playbooks/ansible/cluster-cephfs.yml
- playbooks/ansible/roles/sit.cephfs/tasks/new_volume.yml
- playbooks/ansible/roles/sit.cephfs/templates/smb_share.conf.j2
- playbooks/ansible/roles/test.sit-test-cases/templates/test-info.yml.j2
https://github.com/ceph/ceph/pull/62105 (and subsequently https://github.com/ceph/ceph/pull/62904) is now merged which introduces `--casesensitive` to optionally make a subvolume case **in**sensitive to suite SMB use cases.
Please note that with this change we create shares with and without case sensitive subvolumes but only expose case **in**sensitive based shares for sit-test-cases. Obviously we avoid creating a share with ceph kernel client mount as it is [unsupported](https://docs.ceph.com/en/latest/cephfs/charmap/#restricting-incompatible-client-access) on top of case **in**sensitive subvolumes. One can set `test_casesensitive_cephfs` variable to expose all shares for test runs. For example,
```
EXTRA_VARS="backend=cephfs.mgr test_casesensitive_cephfs=1 test_sanity_only=1" make test …
```
> cephfs: Create and test against case insensitive subvolumes

- playbooks/settings.yml
This patch removes the requirement of CentOS 8 Stream for the storage nodes of the GPFS backend. That requirement was needed because of an incompatibility of the CentOS 9 Stream's ansible version and the ansible playbooks of the Storage Scale installer.
Updates: #102
> Use default OS for GPFS storage nodes

- playbooks/ansible/roles/sit.cephfs/templates/ceph.smb.cluster.yml.j2
Durable handles are only enabled with `kernel oplocks`, `kernel share modes` and `posix locking` disabled. But with mgr variant `posix locking` was not explicitly disabled and thus few tests failed.
```
smbtorture 4.24.0pre1-GIT-33762753f03
Using seed 1759143394
time: 2025-09-29 10:56:34.770112
test: lock-lease
time: 2025-09-29 10:56:34.770708
time: 2025-09-29 10:56:39.831182
failure: lock-lease [
../../source4/torture/smb2/durable_open.c:2451: status was NT_STATUS_OBJECT_NAME_NOT_FOUND, expected NT_STATUS_OK: ../../source4/torture/smb2/durable_open.c:2451
]
smbtorture 4.24.0pre1-GIT-33762753f03
Using seed 1759143435
time: 2025-09-29 10:57:15.976920
test: lock-oplock
time: 2025-09-29 10:57:15.977286
time: 2025-09-29 10:57:23.846668
failure: lock-oplock [ …
```
> sit.cephfs: Disable posix locking for durable handles
